# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{fax_finder}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Erich L. Timkar"]
  s.date = %q{2011-03-15}
  s.email = %q{erich@hordesoftware.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "Changelog",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "fax_finder-0.0.1.gem",
     "fax_finder.gemspec",
     "lib/fax_finder.rb",
     "lib/fax_finder/request.rb",
     "test/request_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/erichhorde/fax_finder}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{fax_finder}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Provides support MultiTech's FaxFinder server}
  s.test_files = [
    "test/request_test.rb",
     "test/response_test.rb",
     "test/send_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<nokogiri>, ["= 1.4.4"])
      s.add_runtime_dependency(%q<builder>, ["~> 2.1.2"])
      s.add_development_dependency(%q<test-unit>, ["~> 2"])
      s.add_development_dependency(%q<mocha>, [">= 0.9"])
    else
      s.add_dependency(%q<nokogiri>, ["= 1.4.4"])
      s.add_dependency(%q<builder>, ["~> 2.1.2"])
      s.add_dependency(%q<test-unit>, ["~> 2"])
      s.add_dependency(%q<mocha>, [">= 0.9"])
    end
  else
    s.add_dependency(%q<nokogiri>, ["= 1.4.4"])
    s.add_dependency(%q<builder>, ["~> 2.1.2"])
    s.add_dependency(%q<test-unit>, ["~> 2"])
    s.add_dependency(%q<mocha>, [">= 0.9"])
  end
end

